name: Python sanity check and tests

on: [push]

jobs:

  python:
    name: Run tests and check python code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3

      - name: Install dependency
        run: pip install -r requirements.txt

      - name: Install matplotlib
        run: pip install matplotlib

      - name: Install development environment
        run: pip install pytest coverage pycodestyle pyflakes mypy
      
      # - name: Run tests and show coverage report
      #   run: |
      #     coverage run -m pytest --verbose
      #     coverage report *.py
      - name: Run tests and show coverage report
        run: |
          # 启用调试模式
          echo "::group::Running tests with debug output"
          # 添加 PYTHONUNBUFFERED=1 确保即时输出
          PYTHONUNBUFFERED=1 coverage run -m pytest --verbose -s  # 添加 -s 参数禁用输出捕获
          echo "::endgroup::"
          
          echo "::group::Coverage report"
          coverage report *.py
          echo "::endgroup::"
          
      - name: Check code style
        run: pycodestyle .

      - name: Check python file for typical errors
        run: pyflakes .

      # type annotation checks
      - name: Type checks
        run: mypy .

      # if you pretend to make a typed version of your program, you should uncomment these lines:  
      # - name: Strict type checks 
      #   run: mypy . --strict

  markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint markdown files
      uses: actionshub/markdownlint@main
